### ISSUE TITLE
Question: Is it possible to get the binary stream of a class object?

### ISSUE THREAD

**Issue by mariusheil** [raydac/java-binary-block-parser#12]
I just tested to generate java objects from a binary stream, which worked for me after annotating my fields with @Bin(type=BinType.UBYTE) because it doesn't automatically map it to integers. But now I am looking for the opposite direction. Get the binary stream from my class, but I can't seem to find it. Is it implemented?

**Comment by raydac** [comment]
Hello
there is auxiliary class [JBBPOut](https://github.com/raydac/java-binary-block-parser/blob/master/src/main/java/com/igormaznitsa/jbbp/io/JBBPOut.java) wich allows to write different kinds of information into binary stream. The Class has family of Bin() methods which can write object of class which fields marked by @Bin. You can take a look at usage of the class in [its tests](https://github.com/raydac/java-binary-block-parser/blob/master/src/test/java/com/igormaznitsa/jbbp/io/JBBPOutTest.java)

**Comment by raydac** [comment]
did the info help?

**Comment by mariusheil** [comment]
Hi, yes. Sorry for not responding. But after a Bit of evaluation I chose to use Preon for my implementation because it seemed a better fit. I like that it offers encoding and decoding without having to implement it seperately.

Thanks again,
Marius

-----Original Message-----
