### ISSUE TITLE
Parse with multiple custom field type processors ?

### ISSUE THREAD

**Issue by blev007** [raydac/java-binary-block-parser#14]
Hello,
I would like to know if there is a way to use several customer type processors (example: one for float, one for String) in the JBBPParser. 
It seems that the "prepare" method accepts only 1 custom parser.
Thank you in advance for your help.
Best regards,
Bruno

**Comment by raydac** [comment]
Hello
yes, there is auxiliary class called JBBPCustomFieldTypeProcessorAggregator and [provided test for it](https://github.com/raydac/java-binary-block-parser/blob/master/src/test/java/com/igormaznitsa/jbbp/utils/JBBPCustomFieldTypeProcessorAggregatorTest.java) which can be used as example

**Comment by blev007** [comment]
Thanks a lot Igor! It works fine...

Le 14 oct. 2016 16:36, Igor Maznitsa <notifications@github.com> a écrit :Hello
yes, there is auxiliary class called JBBPCustomFieldTypeProcessorAggregator and provided test for it which can be used as example
