### ISSUE TITLE
"Expression is empty" error when using arrays

### ISSUE THREAD

**Issue by timmattison** [raydac/java-binary-block-parser#21]
I have a parent class:

```java
import com.igormaznitsa.jbbp.mapper.Bin;

public class BreakJBBPDslBuilderParent {
    @Bin(outOrder = 1)
    public BreakJBBPDslBuilderChild[] breakJBBPDslBuilderChildArray;
}
```

And a child class:

```java
import com.igormaznitsa.jbbp.mapper.Bin;
import com.igormaznitsa.jbbp.mapper.BinType;

public class BreakJBBPDslBuilderChild {
    @Bin(outOrder = 1, comment = "Reserved", type = BinType.BYTE)
    public byte reserved;
}
```

If I try to use the JBBPDslBuilder on the parent class like this:

```java
JBBPDslBuilder.Begin().AnnotatedClass(BreakJBBPDslBuilderParent.class).End();
```

I get an IllegalArgumentException with the message "Expression is empty" that is thrown by this line:

https://github.com/raydac/java-binary-block-parser/blob/790058d289ee8ebae1c4fc8356d4180d77520392/jbbp/src/main/java/com/igormaznitsa/jbbp/utils/JBBPDslBuilder.java#L115

Is this the correct way I'd use the JBBPDslBuilder to work with a structure that has arrays in it?

**Comment by raydac** [comment]
and what do you use as child class? you have provided duplication of parent class instead of child class

**Comment by raydac** [comment]
if you have an array field then DSL builder needs information about length of the array and it should be provided through expression in `extra` attribute
```
 class BreakJBBPDslBuilder {
      @Bin(outOrder = 1, comment = "Reserved", type = BinType.BIT_ARRAY, extra = "4")
      public byte[] reserved;
    }
```

**Comment by timmattison** [comment]
I will update that in a minute. But the child class should just have a single byte field in it.

**Comment by timmattison** [comment]
Updated the child object.  I was using this with the binary code I committed on another branch and the output I get from that is this:

```
breakJBBPDslBuilderChildArray [_] { BYTE reserved; } 
```

To me that makes the most sense.  Can this be supported?  I'd like to combine efforts here and have this wrapped into your library rather than maintain the external interface I built.

**Comment by timmattison** [comment]
If you check out that branch and want to simply run this in a test to see what it does you can use this JUnit test code:

```java
import com.timmattison.iridiumpoc.sbd.BreakJBBPDslBuilderParent;
import org.junit.Test;

import java.io.IOException;

public class BinaryTest {
    @Test
    public void test1() throws IOException {
        System.out.println(new BreakJBBPDslBuilderParent().getFormat());
    }
}
```

**Comment by raydac** [comment]
I have improved message in the exception to provide more information what does mean the error and how to fix

**Comment by timmattison** [comment]
If the field is going to be an array without a fixed size (e.g. a structure that repeats 0 or more times) what is the size I should specify there?  Do I use the underscore like the DSL?

**Comment by raydac** [comment]
if array should be read till end of stream then underscore should be used, extra="_"
