### ISSUE TITLE
Strings in other codecs

### ISSUE THREAD

**Issue by flozano** [raydac/java-binary-block-parser#27]
Thanks for your library. We are upgrading from 1.3 version of your library and we have custom field parsers for explicit ASCII/ISO-8859-1 and UTF-8 strings.

From your implementation, I see "stringj" works just for UTF-8. Is my understanding correct and we should keep our own parsers if we want explicit support for other codecs?

**Comment by raydac** [comment]
`stringj` was added to provide default way to write and read java string with the library, it even writes length of string in internal pack form
in your case it is better to implement own format especially because its length can be provided in different ways

**Comment by raydac** [comment]
I have added example of parsing strings in custom format

**Comment by flozano** [comment]
Thanks!
