### ISSUE TITLE
JBBPByteOrder may add nativeOrder and inheritOrder

### ISSUE THREAD

**Issue by wjtxyz** [raydac/java-binary-block-parser#28]
JBBPOut use the Object's @Bin annotation ByteOrder instead of inherit the ByteOrder from JBBPOut constructor when call JBBPOut.Bin(Object)

example:

`   
      
       byte[] bins = JBBPOut.BeginBin(JBBPByteOrder.LITTLE_ENDIAN).Int(123).Bin(new CommandData(123)).End().toByteArray();
       //actually, bins=[123, 0, 0, 0, 0, 0, 0, 123], but i want bins=[123, 0, 0, 0, 123, 0, 0, 0]

     static class CommandData{
        @Bin(order = 1)
        int data;

        public CommandData(int data) {
            this.data = data;
        }
    }
`

**Comment by raydac** [comment]
am I correct that you have @Bin annotated object where directly defined ByteOrder and you want override order provided in @Bin by order provided in JBBPOut?

**Comment by wjtxyz** [comment]
> am I correct that you have `@Bin` annotated object where directly defined ByteOrder and you want override order provided in `@Bin` by order provided in JBBPOut?

yes

**Comment by raydac** [comment]
I have added into 2.0.2-SNAPSHOT new method `JBBPOut#BinForceByteOrder`
