### ISSUE TITLE
how to set JBBPByteOrder  for JBBPParser ? 

### ISSUE THREAD

**Issue by leepwang** [raydac/java-binary-block-parser#31]
hello:

byte[] data,is generated by JBBPOut, which use JBBPByteOrder.LITTLE_ENDIAN;
how to parse ? I can not find any test case in JBBPMapperTest.java

thanks

**Comment by raydac** [comment]
if would be good to provide some example how you processing data
you parsing by script, then just mark fields by `>` to show parser that they are big-endian ones, like `>int a;`

**Comment by raydac** [comment]
@leepwang what news?

**Comment by leepwang** [comment]
thanks, got it
