### ISSUE TITLE
Error running gradle plugin task jbbpGenerate in gradle 7.4.2

### ISSUE THREAD

**Issue by danhallin** [raydac/java-binary-block-parser#38]
Works in gradle 6.7.1
Gives error in gradle 7.4.2

    > Task :myTask:jbbpGenerate FAILED

    FAILURE: Build failed with an exception.

    What went wrong:
    * A problem was found with the configuration of task ':myTask:jbbpGenerate' (type 'JBBPGenerateTask').
    - In plugin 'com.igormaznitsa.gradle.jbbp' type 'com.igormaznitsa.jbbp.plugin.gradle.JBBPGenerateTask' field 'addSource' without corresponding getter has been annotated with @Input, @Optional.
    
    Reason: Annotations on fields are only used if there's a corresponding getter for the field.
    
    Possible solutions:
      1. Add a getter for field 'addSource'.
      2. Remove the annotations on 'addSource'.
    
    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#ignored_annotations_on_field for more details about this problem.

**Comment by raydac** [comment]
I will add getter, still can't publish the plugin version in gradle portal for strange error "JBBPPlugin.java is a duplicate but no duplicate handling strategy has been set"

**Comment by raydac** [comment]
I managed publish 2.04 plugin version, you can try

**Comment by raydac** [comment]
@danhallin is new version ok?
