### ISSUE TITLE
Use child class for parsing will throw java.lang.IllegalStateException: There is not any opened struct

### ISSUE THREAD

**Issue by shute001** [raydac/java-binary-block-parser#42]
When I use a child class for parsing will throw java.lang.IllegalStateException: There is not any opened struct. Below are my test code.
@Bin
@Getter
@Setter
public class Parent {
    @Bin(order = 1, type = BinType.USHORT, comment = "Size of package header")
    int headerSize;
}

@Bin
@Getter
@Setter
public class Child  extends Parent {
    @Bin(order = 2, type = BinType.BYTE_ARRAY, arraySizeExpr = "1024")
    String body;
}

public class Test {

    @Test
    public void testParse() {
        byte[] data = new byte[] {0x12, 0x34, 0x56, 0x7F};
        final JBBPParser parser = JBBPParser.prepare(JBBPDslBuilder.Begin().AnnotatedClass(Child.class).End());
        JBBPFieldStruct parsed = parser.parse(data);

        final MenuPackageTwo parsedPackage = parsed.findFieldForNameAndType("Child", JBBPFieldStruct.class).mapTo(new Child());
}
}

**Comment by raydac** [comment]
reproducible, thanks a lot, I will check

**Comment by raydac** [comment]
I have fixed the issue, you can try 2.0.6-SNAPSHOT and if all is ok then I will make release during the weekend

**Comment by shute001** [comment]
I have used 2.0.6-SNAPSHOT try agaign, it's ok now. Thanks for the quick fix.

**Comment by raydac** [comment]
release 2.0.6 is out
