### ISSUE TITLE
Unpack float with endian

### ISSUE THREAD

**Issue by zavdimka** [raydac/java-binary-block-parser#43]
I'm working with esp 32 and have task to unpack c structure on Android. 
With python & struct it's very easy
` struct.unpack("<cffhhhhfffccc", message)`
But I have failed to make it with this library. To make it work with this lib I need to unpack to integer using `"<int"` and then use `Float.intBitsToFloat `to this value. It's not so comfortable and readable code when you have a lot of structure fields. 
Could you add `"<floatj"` behaves same as in python struct packet, please?
**Expected behavior**
Byte array - 00 00 80 3f
parse with "<floatj" give 1.0
**actual behavior**
parse with "<floatj" give

**Comment by raydac** [comment]
what was the problem in the case?

**Comment by zavdimka** [comment]
I'm sorry, it was my mistake. I try to put endian into to class after @Bin description in brackets but not in parser string.
After adding endian in parser string everything works fine.
