### ISSUE TITLE
Provide way to limit array size for whole stream array read

### ISSUE THREAD

**Issue by slaft** [raydac/java-binary-block-parser#44]
Hello

I'm trying to limit the length of arrays created by JBBP.

I was able to do it for JBBP types that way:
```java
public class CustomJBBPBitInputStream extends JBBPBitInputStream {

    public CustomJBBPBitInputStream(InputStream in, JBBPBitOrder order) {
        super(in, order);
    }

    @Override
    public boolean[] readBoolArray(final int items) throws IOException {
        // validation here
        return super.readBoolArray(items);
    }
...
}

// Used like this:
parser.parse(new CustomJBBPBitInputStream(new ByteArrayInputStream(input), bitOrder));
```

But I couldn't find a way for arrays of structures and arrays without a defined size (`[_]`).
Do you see a way to do that? Otherwise is a change possible?
(I use the latest version.)

Thanks for your help.

**Comment by raydac** [comment]
I didn't provide way to limit size of array and imho it is a good idea to provide such one.
as a workaround for parsing through script you could try to use **var** type and [JBBPVarFieldProcessor.](https://github.com/raydac/java-binary-block-parser/blob/master/jbbp/src/main/java/com/igormaznitsa/jbbp/JBBPVarFieldProcessor.java) which can be provided as a parameter during parsing, as an example you can take a look at [java class parse test](https://github.com/raydac/java-binary-block-parser/blob/master/jbbp/src/test/java/com/igormaznitsa/jbbp/it/ClassParsingTest.java)

**Comment by raydac** [comment]
I have improved JBBP and added [JBBPArraySizeLimiter](https://github.com/raydac/java-binary-block-parser/blob/master/jbbp/src/main/java/com/igormaznitsa/jbbp/io/JBBPArraySizeLimiter.java) which can be provided for JBBPBitInputStream read array methods and for JBBPParser to limit whole stream array read, it will be published in 2.1.0 release

**Comment by slaft** [comment]
Thanks a lot! (And sorry for the late reply, I've been on holiday.)

With the changes you've made, it's also possible to limit the length of arrays defined via expressions (using JBBPParserExpressionArraySizeController), is that correct?
Do you think it would make sense to extend this type of control to fixed-size arrays as well?

To give you more context (as I'm not sure my question makes sense), in my case the script is user-defined, and I want to restrict what the user can do to protect my service (but maybe there's a lot more than array size I should worry about).

**Comment by raydac** [comment]
if you want to check statically defined array sizes, you can do some trick with visitor of compiled block which I use to generated java classes
```java
    JBBPParser parser = JBBPParser.prepare("byte[100] one; byte [1000000] two;");
    CompiledBlockVisitor visitor = new CompiledBlockVisitor(0, parser.getCompiledBlock()){
      @Override
      public void visitPrimitiveField(int offsetInCompiledBlock, int primitiveType,
                                      JBBPNamedFieldInfo nullableNameFieldInfo,
                                      JBBPByteOrder byteOrder,
                                      boolean readWholeStreamAsArray,
                                      boolean altFieldType,
                                      JBBPIntegerValueEvaluator nullableArraySize) {
        if (!readWholeStreamAsArray
            && nullableArraySize != null
            && nullableArraySize.getClass().getSimpleName().equals("IntConstValueEvaluator")) {
            int size = nullableArraySize.eval(null, offsetInCompiledBlock, null, null);
            if (size > 10000) {
              throw new IllegalArgumentException("Too big array: " + nullableNameFieldInfo);
            }
        }
      }
    };
    visitor.visit();
``` 
in the code above the exception will be thrown for too big static size of array, keep in mind that users can write something `array1 [1000] { byte [1000] array2; }` and if you want check it then improve visitor for structure processing

**Comment by slaft** [comment]
Thanks again for your help. (And that's noted for arrays of structures, I'll definitely check that too).

**Comment by raydac** [comment]
I have made minor refactoring and added util method `JBBPUtils#findMaxStaticArraySize` into 2.1.1-SNAPSHOT

**Comment by slaft** [comment]
Thanks, it's very helpful!

**Comment by raydac** [comment]
so, it looks like that since 3.0.0 version I have provided ways to detect too long arrays for dynamic and static variants
