### ISSUE TITLE
Doc : how to unpack ?

### ISSUE THREAD

**Issue by aristide** [raydac/java-binary-block-parser#8]
Hi @raydac this library look really cool !

But can i run it with an Android project? 

Where is the doc that shows how to unpack? I'm just seeing  how to [pack](http://stackoverflow.com/questions/3209898/java-equivalent-of-pythons-struct-pack) 

thks

**Comment by raydac** [comment]
@aristide  the library is compatible with android (I tried with android 2.1), there are examples how to unpack some formats in the integration tests folder https://github.com/raydac/java-binary-block-parser/tree/master/src/test/java/com/igormaznitsa/jbbp/it
if you don't find example covering your case then just write me directly and I will explain how to work with some cases

**Comment by aristide** [comment]
thks @raydac
